apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catfacts-cicd
  namespace: argocd
spec:
  destination:
    namespace: tekton-pipelines
    server: 'https://kubernetes.default.svc'
  source:
    path: ci/tekton
    repoURL: 'https://github.com/Christian-Bull/catfacts'
    targetRevision: HEAD
  project: cbull
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
