apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catfacts
  namespace: argocd
spec:
  destination:
    name: catfacts
    namespace: catfacts
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests
    repoURL: 'https://github.com/Christian-Bull/catfacts'
    targetRevision: HEAD
  project: cbull
  syncPolicy:
    automated:
      prune: true
      selfHeal: true