apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reactbot
  namespace: argocd-cbull
spec:
  source:
    repoURL: 'https://github.com/Christian-Bull/slack-reactbot.git'
    path: manifests
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cbull
  project: cbull
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
